CREATE DATABASE Student;
USE Student;
CREATE TABLE Stud_det(Student_id INT,Roll_No VARCHAR(50),Student_Name VARCHAR(50),Dept_Name VARCHAR(50),Course VARCHAR(50),Year VARCHAR(50),Sem VARCHAR(50),Division VARCHAR(50),Gender VARCHAR(50),DOB VARCHAR(50),Email VARCHAR(50),Phone VARCHAR(50) NOT NULL,Address VARCHAR(50),PRIMARY KEY(Student_id));
SHOW TABLES;
SELECT*FROM stud_det;
