CREATE DATABASE Student2;
USE Student2;
CREATE TABLE Stud_det(Student_id INT,Roll_No VARCHAR(50),Student_Name VARCHAR(50),Dept_Name VARCHAR(50),Course VARCHAR(50),Year VARCHAR(50),Sem VARCHAR(50),Division VARCHAR(50),Gender VARCHAR(50),DOB VARCHAR(50),Email VARCHAR(50),Phone VARCHAR(50) NOT NULL,Address VARCHAR(50),PRIMARY KEY(Student_id));
CREATE TABLE Teacher(Teach_id INT,Teacher_Name VARCHAR(50),Education VARCHAR(50),Department VARCHAR(50),Teacher_Salary VARCHAR(50),PRIMARY KEY(Teach_id));
ALTER TABLE Stud_det ADD COLUMN Teach_id INT;
ALTER TABLE stud_det ADD FOREIGN KEY(Teach_id) REFERENCES Teacher(Teach_id);
INSERT INTO Teacher(Teach_id,Teacher_Name,Education,Department,Teacher_Salary) VALUES (1,"Mr.Sahil Jadhav","Btech","IT","50000");
INSERT INTO Teacher(Teach_id,Teacher_Name,Education,Department,Teacher_Salary) VALUES (2,"Mrs.Anjali Raut","Mtech","CS","80000");
INSERT INTO Teacher(Teach_id,Teacher_Name,Education,Department,Teacher_Salary) VALUES (3,"Mrs.Saee Jadhav","Mtech","AIML","100000");
INSERT INTO Teacher(Teach_id,Teacher_Name,Education,Department,Teacher_Salary) VALUES (4,"Mr.Avinash Kupte","Btech","AIDS","190000");
INSERT INTO Teacher(Teach_id,Teacher_Name,Education,Department,Teacher_Salary) VALUES (5,"Mr.Raj Kale","BE","IT","90000");
SELECT * FROM departments;
ALTER TABLE Stud_det MODIFY COLUMN Division VARCHAR(2);
ALTER TABLE Stud_det ADD CONSTRAINT gmail CHECK (Email REGEXP '^[a-zA-Z0-9._%+-]+@gmail\.com$');
ALTER TABLE Stud_det ADD CONSTRAINT valid_name CHECK (Student_Name REGEXP '^[A-Za-z]+ [A-Za-z]+$');
ALTER TABLE Stud_det ADD CONSTRAINT valid_phone_number CHECK (Phone REGEXP '^[0-9]{10}$');
ALTER TABLE Stud_det ADD CONSTRAINT valid_date_of_birth CHECK (DOB REGEXP '^(19|20)\d\d/(0[1-9]|1[0-2])/(0[1-9]|[12][0-9]|3[01])$');
ALTER TABLE Stud_det MODIFY COLUMN DOB DATE;
ALTER TABLE Stud_det DROP CONSTRAINT valid_date_of_birth;
CREATE TABLE departments (Dept_Name VARCHAR(255) PRIMARY KEY);
DELETE FROM Teacher WHERE Teach_id=5;
DELETE FROM departments WHERE Dept_Name='civil';
ALTER TABLE stud_det ADD FOREIGN KEY(Dept_Name) REFERENCES departments(Dept_Name);
ALTER TABLE Teacher ADD FOREIGN KEY(Department) REFERENCES departments(Dept_Name);
DESCRIBE STUD_det;
SHOW TABLES; 